# Generated by Django 5.2.14 on 2026-05-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(max_length=100)),
                ('idade_pet', models.CharField(max_length=20)),
                ('especie', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=20)),
                ('peso', models.CharField(max_length=20)),
                ('raca', models.CharField(max_length=50)),
                ('vacinas', models.CharField(max_length=200)),
                ('doencas', models.CharField(max_length=200)),
                ('medicamentos', models.CharField(max_length=200)),
                ('cirurgias', models.CharField(max_length=200)),
                ('alergias', models.CharField(max_length=200)),
                ('atendimento', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('nome_dono', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
    ]
